version: '3.2'
services:
    nicos-cache:
       image: pshcyrill/nicos-cache:latest
       network_mode: host
       ports:
        - "14869:14869"
       volumes:
        - ./nicos_pnpi:/usr/src/nicos/nicos_pnpi
        - ./log:/log
        - ./data:/data
	- ./configs:/configs
       environment:
        - INSTRUMENT=nicos_pnpi.tex2

    nicos-daemon:
       image: pshcyrill/nicos-daemon:latest
       depends_on:
        - nicos-cache
       network_mode: host
       volumes:
        - ./nicos_pnpi:/usr/src/nicos/nicos_pnpi
        - ./log:/log
        - ./data:/data
       environment:
        - INSTRUMENT=nicos_pnpi.tex2

    nicos-poller:
       image: pshcyrill/nicos-poller:latest
       network_mode: host
       depends_on:
        - nicos-daemon
       volumes:
        - ./nicos_pnpi:/usr/src/nicos/nicos_pnpi
        - ./log:/log
        - ./data:/data
       environment:
        - INSTRUMENT=nicos_pnpi.tex2

    nicos-elog:
       image: pshcyrill/nicos-elog:latest
       network_mode: host
       depends_on:
        - nicos-cache
       volumes:
        - ./nicos_pnpi:/usr/src/nicos/nicos_pnpi
        - ./log:/log
        - ./data:/data
       environment:
        - INSTRUMENT=nicos_pnpi.tex2

    nicos-watchdog:
       image: pshcyrill/nicos-watchdog:latest
       network_mode: host
       depends_on:
        - nicos-cache
       volumes:
        - ./nicos_pnpi:/usr/src/nicos/nicos_pnpi
        - ./log:/log
        - ./data:/data
       environment:
        - INSTRUMENT=nicos_pnpi.tex2
       