version: '3.2'
services:
    nicos-cache:
       image: pshcyrill/nicos-cache:test
       network_mode: host
       ports:
        - "14869:14869"
       volumes:
        - ./nicos_pnpi:/usr/src/nicos/nicos_pnpi
        - ./log:/log
        - ./data:/data
       environment:
        - INSTRUMENT=nicos_pnpi.demo

    nicos-daemon:
       image: pshcyrill/nicos-daemon:test
       depends_on:
        - nicos-cache
       network_mode: host
       volumes:
        - ./nicos_pnpi:/usr/src/nicos/nicos_pnpi
        - ./log:/log
        - ./data:/data
       environment:
        - INSTRUMENT=nicos_pnpi.demo

    nicos-poller:
       image: pshcyrill/nicos-poller:test
       network_mode: host
       depends_on:
        - nicos-daemon
       volumes:
        - ./nicos_pnpi:/usr/src/nicos/nicos_pnpi
        - ./log:/log
        - ./data:/data
       environment:
        - INSTRUMENT=nicos_pnpi.demo

    nicos-elog:
       image: pshcyrill/nicos-elog:test
       network_mode: host
       depends_on:
        - nicos-cache
       volumes:
        - ./nicos_pnpi:/usr/src/nicos/nicos_pnpi
        - ./log:/log
        - ./data:/data
       environment:
        - INSTRUMENT=nicos_pnpi.demo

    nicos-watchdog:
       image: pshcyrill/nicos-watchdog:test
       network_mode: host
       depends_on:
        - nicos-cache
       volumes:
        - ./nicos_pnpi:/usr/src/nicos/nicos_pnpi
        - ./log:/log
        - ./data:/data
       environment:
        - INSTRUMENT=nicos_pnpi.demo
       